###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"

volumes:
  pg-data:

services:
  postgres:
    image: postgres:11.7
    container_name: laravel_database
    working_dir: /app
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks: 
      - laravel-network
    env_file:
      - ./backend/.env
    ports:
      - "8084:5432"

  webserver:
    image: nginx:alpine
    container_name: laravel_server
    working_dir: /app
    networks: 
      - laravel-network
    volumes:
      - .:/app
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  backend:
    build: phpdocker/backend
    container_name: laravel_fpm
    networks: 
      - laravel-network
    volumes:
      - ./backend:/app
      - ./phpdocker/backend/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

networks: 
  laravel-network:
    driver: bridge